import type { Metadata } from "next";
import "./globals.css";
import "swiper/css";

import { poppins } from "@/fonts/Fonts";
import ReduxProvider from "@/providers/reduxProvider";
import ProductModalGlobal from "@/components/product-modal-global";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-poppins antialiased`}>
        <ReduxProvider>
          <Toaster position="top-right" theme="system" />
          {children}
          <ProductModalGlobal />
        </ReduxProvider>
      </body>
    </html>
  );
}
