export const COUNTRIES = [
  { value: "Pakistan", label: "Pakistan" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "Nepal", label: "Nepal" },
  { value: "Sri Lanka", label: "Sri Lanka" },
  { value: "Afghanistan", label: "Afghanistan" },
  { value: "Bhutan", label: "Bhutan" },
  { value: "Maldives", label: "Maldives" },
  { value: "Indonesia", label: "Indonesia" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Thailand", label: "Thailand" },
  { value: "Vietnam", label: "Vietnam" },
  { value: "Philippines", label: "Philippines" },
  { value: "United Arab Emirates", label: "United Arab Emirates" },
  { value: "Saudi Arabia", label: "Saudi Arabia" },
  { value: "Other", label: "Other" },
];

export const STATES = {
  Pakistan: [
    { value: "Punjab", label: "Punjab" },
    { value: "Sindh", label: "Sindh" },
    { value: "KPK", label: "KPK" },
    { value: "Balochistan", label: "Balochistan" },
    { value: "Other", label: "Other" },
  ],
  Bangladesh: [
    { value: "Dhaka", label: "Dhaka" },
    { value: "Chittagong", label: "Chittagong" },
    { value: "Sylhet", label: "Sylhet" },
    { value: "Other", label: "Other" },
  ],
  Nepal: [
    { value: "Bagmati", label: "Bagmati" },
    { value: "Gandaki", label: "Gandaki" },
    { value: "Lumbini", label: "Lumbini" },
    { value: "Other", label: "Other" },
  ],
  "Sri Lanka": [
    { value: "Western", label: "Western" },
    { value: "Central", label: "Central" },
    { value: "Southern", label: "Southern" },
    { value: "Other", label: "Other" },
  ],
  Afghanistan: [
    { value: "Kabul", label: "Kabul" },
    { value: "Herat", label: "Herat" },
    { value: "Kandahar", label: "Kandahar" },
    { value: "Other", label: "Other" },
  ],
  Bhutan: [
    { value: "Thimphu", label: "Thimphu" },
    { value: "Paro", label: "Paro" },
    { value: "Punakha", label: "Punakha" },
    { value: "Other", label: "Other" },
  ],
  Maldives: [
    { value: "Malé", label: "Malé" },
    { value: "Addu City", label: "Addu City" },
    { value: "Fuvahmulah", label: "Fuvahmulah" },
    { value: "Other", label: "Other" },
  ],
  Indonesia: [
    { value: "Jakarta", label: "Jakarta" },
    { value: "West Java", label: "West Java" },
    { value: "Bali", label: "Bali" },
    { value: "Other", label: "Other" },
  ],
  Malaysia: [
    { value: "Selangor", label: "Selangor" },
    { value: "Penang", label: "Penang" },
    { value: "Sabah", label: "Sabah" },
    { value: "Other", label: "Other" },
  ],
  Thailand: [
    { value: "Bangkok", label: "Bangkok" },
    { value: "Chiang Mai", label: "Chiang Mai" },
    { value: "Phuket", label: "Phuket" },
    { value: "Other", label: "Other" },
  ],
  Vietnam: [
    { value: "Hanoi", label: "Hanoi" },
    { value: "Ho Chi Minh", label: "Ho Chi Minh" },
    { value: "Da Nang", label: "Da Nang" },
    { value: "Other", label: "Other" },
  ],
  Philippines: [
    { value: "Metro Manila", label: "Metro Manila" },
    { value: "Cebu", label: "Cebu" },
    { value: "Davao", label: "Davao" },
    { value: "Other", label: "Other" },
  ],
  "United Arab Emirates": [
    { value: "Dubai", label: "Dubai" },
    { value: "Abu Dhabi", label: "Abu Dhabi" },
    { value: "Sharjah", label: "Sharjah" },
    { value: "Other", label: "Other" },
  ],
  "Saudi Arabia": [
    { value: "Riyadh", label: "Riyadh" },
    { value: "Jeddah", label: "Jeddah" },
    { value: "Dammam", label: "Dammam" },
    { value: "Other", label: "Other" },
  ],
};

export const CITIES = {
  Pakistan: [
    { value: "Karachi", label: "Karachi" },
    { value: "Lahore", label: "Lahore" },
    { value: "Islamabad", label: "Islamabad" },
    { value: "Faisalabad", label: "Faisalabad" },
    { value: "Rawalpindi", label: "Rawalpindi" },
    { value: "Other", label: "Other" },
  ],
  Bangladesh: [
    { value: "Dhaka", label: "Dhaka" },
    { value: "Chittagong", label: "Chittagong" },
    { value: "Sylhet", label: "Sylhet" },
    { value: "Other", label: "Other" },
  ],
  Nepal: [
    { value: "Kathmandu", label: "Kathmandu" },
    { value: "Pokhara", label: "Pokhara" },
    { value: "Lalitpur", label: "Lalitpur" },
    { value: "Other", label: "Other" },
  ],
  "Sri Lanka": [
    { value: "Colombo", label: "Colombo" },
    { value: "Kandy", label: "Kandy" },
    { value: "Galle", label: "Galle" },
    { value: "Other", label: "Other" },
  ],
  Afghanistan: [
    { value: "Kabul", label: "Kabul" },
    { value: "Herat", label: "Herat" },
    { value: "Kandahar", label: "Kandahar" },
    { value: "Other", label: "Other" },
  ],
  Bhutan: [
    { value: "Thimphu", label: "Thimphu" },
    { value: "Paro", label: "Paro" },
    { value: "Punakha", label: "Punakha" },
    { value: "Other", label: "Other" },
  ],
  Maldives: [
    { value: "Malé", label: "Malé" },
    { value: "Hithadhoo", label: "Hithadhoo" },
    { value: "Fuvahmulah", label: "Fuvahmulah" },
    { value: "Other", label: "Other" },
  ],
  Indonesia: [
    { value: "Jakarta", label: "Jakarta" },
    { value: "Surabaya", label: "Surabaya" },
    { value: "Denpasar", label: "Denpasar" },
    { value: "Other", label: "Other" },
  ],
  Malaysia: [
    { value: "Kuala Lumpur", label: "Kuala Lumpur" },
    { value: "George Town", label: "George Town" },
    { value: "Kota Kinabalu", label: "Kota Kinabalu" },
    { value: "Other", label: "Other" },
  ],
  Thailand: [
    { value: "Bangkok", label: "Bangkok" },
    { value: "Chiang Mai", label: "Chiang Mai" },
    { value: "Phuket", label: "Phuket" },
    { value: "Other", label: "Other" },
  ],
  Vietnam: [
    { value: "Hanoi", label: "Hanoi" },
    { value: "Ho Chi Minh City", label: "Ho Chi Minh City" },
    { value: "Da Nang", label: "Da Nang" },
    { value: "Other", label: "Other" },
  ],
  Philippines: [
    { value: "Manila", label: "Manila" },
    { value: "Cebu City", label: "Cebu City" },
    { value: "Davao City", label: "Davao City" },
    { value: "Other", label: "Other" },
  ],
  "United Arab Emirates": [
    { value: "Dubai", label: "Dubai" },
    { value: "Abu Dhabi", label: "Abu Dhabi" },
    { value: "Sharjah", label: "Sharjah" },
    { value: "Other", label: "Other" },
  ],
  "Saudi Arabia": [
    { value: "Riyadh", label: "Riyadh" },
    { value: "Jeddah", label: "Jeddah" },
    { value: "Dammam", label: "Dammam" },
    { value: "Other", label: "Other" },
  ],
};
